#!/bin/sh

#--------------------------------------------------------------------------------
# GENERAL 
#--------------------------------------------------------------------------------
alias aal='nvim ~/Dotfiles/conf/aliasrc' 
alias xcp='xclip -selection clipboard'
alias cpwd="pwd | sed 's| |\\\ |g' | xclip -selection clipboard " 
alias so='source ~/.zshrc'
# Edit
alias v=nvim
alias vimdiff='nvim -d'
# Move
alias ran='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias rna='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias cds='cd ~/.scripts'
# Languages
alias R="R --quiet"
alias py='python3'
alias py27='source ~/Lib/py27/bin/activate'

# ----------------------
# Git Aliases
# ----------------------
# https://jonsuh.com/blog/git-command-line-shortcuts/
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit --message'
alias gco='git checkout'
alias gd='git diff'
alias gda='git diff HEAD'
alias glg='git log --graph --oneline --decorate --all'
alias gp='git push'
alias gs='git status'
